
jfxninja_cms_admin:
    pattern:  /{admin}/
    defaults: { _controller: JfxNinjaCMSBundle:Default:index}
    requirements:
      admin: ^admin$

#Content Controller
jfxninja_cms_admin_content_attributes:
    pattern:  /admin/content/attributes/{securekey}/{_locale}
    defaults: { _controller: JfxNinjaCMSBundle:ContentTypeAttributes:edit, mode: edit, _locale: %jfxninja.default_locale% }

jfxninja_cms_admin_content_new:
    pattern:  /admin/content/new
    defaults: { _controller: JfxNinjaCMSBundle:Content:new, mode: new }

jfxninja_cms_admin_content_edit:
    pattern:  /admin/content/edit/{securekey}/{_locale}
    defaults: { _controller: JfxNinjaCMSBundle:Content:edit, mode: edit, _locale: %jfxninja.default_locale% }

jfxninja_cms_admin_content_delete:
    pattern:  /admin/content/delete/{securekey}
    defaults: { _controller: JfxNinjaCMSBundle:Content:delete, mode: delete }


jfxninja_cms_admin_content_list_default:
    pattern:  /admin/content/
    defaults: { _controller: JfxNinjaCMSBundle:Content:index, mode: list, _locale: %jfxninja.default_locale%, securekey: not-specified }


jfxninja_cms_admin_content_list:
    pattern:  /admin/content/{securekey}/{_locale}
    defaults: { _controller: JfxNinjaCMSBundle:Content:index, mode: list, _locale: %jfxninja.default_locale%, securekey: not-specified }


#CMS Admin Navigation
jfxninja_cms_admin_wysiwyg_image_upload:
    pattern:  /admin/wysiwyg_image_upload/{sfid}
    defaults: { _controller: JfxNinjaCMSBundle:WYSIWYGImageUpload:storeImage }


#ContentType Controller
jfxninja_cms_admin_contentTypes_list:
    pattern:  /admin/content-types/
    defaults: { _controller: JfxNinjaCMSBundle:ContentTypes:index, mode: list }

jfxninja_cms_admin_contentTypes_new:
    pattern:  /admin/content-types/new
    defaults: { _controller: JfxNinjaCMSBundle:ContentTypes:new, mode: new }

jfxninja_cms_admin_contentTypes_edit:
    pattern:  /admin/content-types/edit/{securekey}/{_locale}
    defaults: { _controller: JfxNinjaCMSBundle:ContentTypes:edit, mode: edit, _locale: %jfxninja.default_locale% }

jfxninja_cms_admin_contentTypes_delete:
    pattern:  /admin/content-types/delete/{securekey}
    defaults: { _controller: JfxNinjaCMSBundle:ContentTypes:delete, mode: delete }


#Domains Controller
jfxninja_cms_admin_domains_list:
    pattern:  /admin/domains/
    defaults: { _controller: JfxNinjaCMSBundle:Domains:index, mode: list }

jfxninja_cms_admin_domains_new:
    pattern:  /admin/domains/new
    defaults: { _controller: JfxNinjaCMSBundle:Domains:new, mode: new }

jfxninja_cms_admin_domains_edit:
    pattern:  /admin/domains/edit/{securekey}
    defaults: { _controller: JfxNinjaCMSBundle:Domains:edit, mode: edit }

jfxninja_cms_admin_domains_delete:
    pattern:  /admin/domains/delete/{securekey}
    defaults: { _controller: JfxNinjaCMSBundle:Domains:delete, mode: delete }


#Languages Controller
jfxninja_cms_admin_languages_list:
    pattern:  /admin/languages/
    defaults: { _controller: JfxNinjaCMSBundle:Languages:index, mode: list }

jfxninja_cms_admin_languages_new:
    pattern:  /admin/languages/new
    defaults: { _controller: JfxNinjaCMSBundle:Languages:new, mode: new }

jfxninja_cms_admin_languages_edit:
    pattern:  /admin/languages/edit/{securekey}
    defaults: { _controller: JfxNinjaCMSBundle:Languages:edit, mode: edit }

jfxninja_cms_admin_languages_delete:
    pattern:  /admin/languages/delete/{securekey}
    defaults: { _controller: JfxNinjaCMSBundle:Languages:delete, mode: delete }


#Menus Controller
jfxninja_cms_admin_menus_list:
    pattern:  /admin/menus/
    defaults: { _controller: JfxNinjaCMSBundle:Menus:index, mode: list }

jfxninja_cms_admin_menus_new:
    pattern:  /admin/menus/new
    defaults: { _controller: JfxNinjaCMSBundle:Menus:new, mode: new }

jfxninja_cms_admin_menus_edit:
    pattern:  /admin/menus/edit/{securekey}
    defaults: { _controller: JfxNinjaCMSBundle:Menus:edit, mode: edit }

jfxninja_cms_admin_menus_delete:
    pattern:  /admin/menus/delete/{securekey}
    defaults: { _controller: JfxNinjaCMSBundle:Menus:delete, mode: delete }


#MenuItems Controller
jfxninja_cms_admin_menuItems_list:
    pattern:  /admin/menu-items/
    defaults: { _controller: JfxNinjaCMSBundle:MenuItems:index, mode: list }

jfxninja_cms_admin_menuItems_new:
    pattern:  /admin/menu-items/new
    defaults: { _controller: JfxNinjaCMSBundle:MenuItems:new, mode: new }

jfxninja_cms_admin_menuItems_edit:
    pattern:  /admin/menu-items/edit/{securekey}/{_locale}
    defaults: { _controller: JfxNinjaCMSBundle:MenuItems:edit, mode: edit, _locale: %jfxninja.default_locale% }

jfxninja_cms_admin_menuItems_delete:
    pattern:  /admin/menu-items/delete/{securekey}
    defaults: { _controller: JfxNinjaCMSBundle:MenuItems:delete, mode: delete }

jfxninja_cms_admin_menuItems_ajax_contentTypeCategories:
    pattern:  /admin/menu-items/ajax/contentTypeCategories
    defaults: { _controller: JfxNinjaCMSBundle:AjaxValueLists:getContentTypeCategoryFields }

jfxninja_cms_admin_menuItems_ajax_contentTypeCategoryRelatedField:
    pattern:  /admin/menu-items/ajax/ContentTypeCategoryRelatedFields
    defaults: { _controller: JfxNinjaCMSBundle:AjaxValueLists:getContentTypeCategoryRelatedFields }




#Modules Controller
jfxninja_cms_admin_modules_list:
    pattern:  /admin/modules/
    defaults: { _controller: JfxNinjaCMSBundle:Modules:index, mode: list }

jfxninja_cms_admin_modules_new:
    pattern:  /admin/modules/new
    defaults: { _controller: JfxNinjaCMSBundle:Modules:new, mode: new }

jfxninja_cms_admin_modules_edit:
    pattern:  /admin/modules/edit/{securekey}/{_locale}
    defaults: { _controller: JfxNinjaCMSBundle:Modules:edit, mode: edit, _locale: %jfxninja.default_locale% }

jfxninja_cms_admin_modules_delete:
    pattern:  /admin/modules/delete/{securekey}
    defaults: { _controller: JfxNinjaCMSBundle:Modules:delete, mode: delete }

jfxninja_cms_admin_modules_ajax_moduleContentDisplayOptions:
    pattern:  /admin/modules/ajax/moduleContentDisplayOptions
    defaults: { _controller: JfxNinjaCMSBundle:AjaxValueLists:getModuleContentDisplayOptions }

jfxninja_cms_admin_modules_ajax_getModuleFilterValueOptions:
    pattern:  /admin/modules/ajax/getModuleFilterValueOptions
    defaults: { _controller: JfxNinjaCMSBundle:AjaxValueLists:getModuleFilterValueOptions }



#CMS admin CMSForms Controller
jfxninja_cms_admin_cmsforms_list:
    pattern:  /admin/cmsforms/
    defaults: { _controller: JfxNinjaCMSBundle:CMSForms:index, mode: list }

jfxninja_cms_admin_cmsforms_new:
    pattern:  /admin/cmsforms/new
    defaults: { _controller: JfxNinjaCMSBundle:CMSForms:new, mode: new }

jfxninja_cms_admin_cmsforms_edit:
    pattern:  /admin/cmsforms/edit/{securekey}/{_locale}
    defaults: { _controller: JfxNinjaCMSBundle:CMSForms:edit, mode: edit, _locale: %jfxninja.default_locale%  }

jfxninja_cms_admin_cmsforms_delete:
    pattern:  /admin/cmsforms/delete/{securekey}
    defaults: { _controller: JfxNinjaCMSBundle:CMSForms:delete, mode: delete }

#CMS admin User management Controller
jfxninja_cms_admin_users_list:
    pattern:  /admin/users/
    defaults: { _controller: JfxNinjaCMSBundle:Users:index, mode: list }

jfxninja_cms_admin_users_new:
    pattern:  /admin/users/new
    defaults: { _controller: JfxNinjaCMSBundle:Users:new, mode: new }

jfxninja_cms_admin_users_edit:
    pattern:  /admin/users/edit/{securekey}
    defaults: { _controller: JfxNinjaCMSBundle:Users:edit, mode: edit }

jfxninja_cms_admin_users_delete:
    pattern:  /admin/cmsforms/delete/{securekey}
    defaults: { _controller: JfxNinjaCMSBundle:Users:delete, mode: delete }


#CMS Admin Navigation
jfxninja_cms_admin_navigation:
    pattern:  /admin/navigation
    defaults: { _controller: JfxNinjaCMSBundle:AdminNavigation:drawAdminNavigation }



#Generic Entity Manager Controller
jfxninja_cms_admin_entity_manager_index:
    pattern:  /admin/entity-manager/{entity}/
    defaults: { _controller: JfxNinjaCMSBundle:EntityManager:crud, mode: list, sid: null }

jfxninja_cms_admin_entity_manager:
    pattern:  /admin/entity-manager/{entity}/{mode}/{sid}
    defaults: { _controller: JfxNinjaCMSBundle:EntityManager:crud, mode: list, sid: null }



login:
    path:   /login
    defaults:  { _controller: JfxNinjaCMSBundle:Security:login }

login_check:
    path:   /admin/login_check

logout:
    path:   /admin/logout

jfxninja_cms_install:
    pattern: /maintenance/install
    defaults: { _controller: JfxNinjaCMSBundle:Maintenance:cmsInstall }


#Main CMS front controller
jfxninja_cms_frontend:
    pattern:  /{_locale}/{uri}
    defaults: { _controller: JfxNinjaCMSBundle:Front:index, _locale: %jfxninja.default_locale%}
    methods:  [GET]
    requirements:
      uri: ^((?!(admin|login|logout)).)*$
      _locale: en|fr|es


jfxninja_cms_frontend_noloco:
    pattern:  /{uri}
    defaults: { _controller: JfxNinjaCMSBundle:Front:index, _locale: %jfxninja.default_locale%}
    methods: [GET]
    requirements:
      uri: ^((?!(admin|login|logout)).)*$


#Main CMS front controller
jfxninja_cms_frontend_post:
    pattern:  /{_locale}/{uri}
    defaults: { _controller: JfxNinjaCMSBundle:Front:index, _locale: %jfxninja.default_locale%}
    methods: [POST]
    requirements:
      _locale: en|fr|es
      uri: (.+|)


jfxninja_cms_frontend_noloco_post:
    pattern:  /{uri}
    defaults: { _controller: JfxNinjaCMSBundle:Front:index, _locale: %jfxninja.default_locale%}
    methods: [POST]
    requirements:
      _locale: en|fr|es
      uri: (.+|)



