
services:

    jfxninja.cms.kernel.exception_listener:
      class: JfxNinja\CMSBundle\Listener\ExceptionListener
      arguments: [@templating, @kernel, "@request_stack", "@service_container"]
      tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }




    jfxninja.cms.fileuploader:
        class: JfxNinja\CMSBundle\Services\FileUploader

    jfxninja.cms.recordauditor:
        class: JfxNinja\CMSBundle\Services\RecordAuditor
        arguments:    ["@=service('security.context')"]

    jfxninja.cms.localiser:
        class: JfxNinja\CMSBundle\Services\Localiser
        arguments: ["@service_container","@request","@doctrine.orm.entity_manager"]
        scope: request

    jfxninja.cms.helperFunctions:
        class: JfxNinja\CMSBundle\Services\HelperFunctions
        scope: request

    jfxninja.cms.navigation:
        class: JfxNinja\CMSBundle\Services\Navigation
        arguments: ["@jfxninja.cms.localiser","@doctrine.orm.entity_manager","@jfxninja.cms.helperFunctions","@jfxninja.cms.content"]
        scope: request

    jfxninja.cms.module:
        class: JfxNinja\CMSBundle\Services\ModuleService
        arguments: ["@jfxninja.cms.localiser","@doctrine.orm.entity_manager","@jfxninja.cms.helperFunctions","@jfxninja.cms.content","@jfxninja.cms.block","@request_stack","@mailer","@templating"]
        scope: request

    jfxninja.cms.form:
        class: JfxNinja\CMSBundle\Services\CMSFormService
        arguments: ["@jfxninja.cms.localiser","@doctrine.orm.entity_manager","@jfxninja.cms.helperFunctions","@jfxninja.cms.content","@jfxninja.cms.block","@request_stack","@mailer","@templating"]
        scope: request

    jfxninja.cms.content:
        class: JfxNinja\CMSBundle\Services\ContentService
        arguments: ["@jfxninja.cms.localiser","@doctrine.orm.entity_manager","@jfxninja.cms.block","@jfxninja.cms.recordauditor"]
        scope: request

    jfxninja.cms.block:
        class: JfxNinja\CMSBundle\Services\BlockService
        arguments: ["@jfxninja.cms.localiser","@doctrine.orm.entity_manager","@jfxninja.cms.fileuploader","@jfxninja.cms.recordauditor"]
        scope: request


    jfxninja.cms.migration:
        class: JfxNinja\CMSBundle\Services\MigrationService
        arguments: ["@service_container","@doctrine.orm.entity_manager","%kernel.root_dir%"]




    jfxninja_cms.type.multi_langue_text_field:
        class: JfxNinja\CMSBundle\Form\FieldType\MultiLanguageText
        tags:
            - { name: form.type, alias: multiLanguageText }

    jfxninja_cms.type.multi_langue_textarea_field:
        class: JfxNinja\CMSBundle\Form\FieldType\MultiLanguageTextarea
        tags:
            - { name: form.type, alias: multiLanguageTextarea }

    jfxninja_cms.type.multi_langue_choice_field:
        class: JfxNinja\CMSBundle\Form\FieldType\MultiLanguageChoice
        tags:
            - { name: form.type, alias: multiLanguageChoice}

    jfxninja_cms.type.cms_choice_field:
        class: JfxNinja\CMSBundle\Form\FieldType\CMSChoiceField
        tags:
            - { name: form.type, alias:CMSChoice}

    jfxninja_cms.type.CMSFieldFilePath:
        class: JfxNinja\CMSBundle\Form\FieldType\CMSFieldFilePath
        tags:
            - { name: form.type, alias: CMSFieldFilePath }

    jfxninja_cms.type.textarea_extension:
        class: JfxNinja\CMSBundle\Form\Extension\TextareaTypeExtension
        tags:
            - { name: form.type_extension, alias: textarea }




    core.twig.to_array_extension:
        class: JfxNinja\CMSBundle\Twig\Extension\ToArrayExtension
        tags:
            - { name: twig.extension }

    core.twig.jfxninja_formatTextToHTML_extension:
        class: JfxNinja\CMSBundle\Twig\Extension\FormatTextToHTML
        tags:
            - { name: twig.extension }

    core.twig.jfxninja_CrToBr_extension:
        class: JfxNinja\CMSBundle\Twig\Extension\CrToBr
        tags:
            - { name: twig.extension }

#    JfxNinja.cms.language:
#        class: JfxNinja\CMSBundle\Services\SetDefaultLanguage
#        arguments: ["@doctrine.orm.entity_manager","@service_container"]
#        tags:
#            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 30 }