<?php

namespace JfxNinja\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlockFieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockFieldsRepository extends EntityRepository
{
}
