<?php

namespace SSone\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlocksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocksRepository extends EntityRepository
{

    public function findBySecurekey($securekey)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM SSoneCMSBundle:Block c WHERE c.securekey = :securekey'
            )->setParameter('securekey', $securekey)
            ->getSingleResult();
    }


    public function getItemsForListTable()
    {
        $data['type'] = "Content Blocks";
        $data['columns'] = array(
            "Name"=>"name",
            "ID"=>"id"
        );
        $data['items'] = $this->getEntityManager()
            ->createQuery(
                'SELECT c.name, c.id, c.securekey FROM SSoneCMSBundle:Block c ORDER BY c.name ASC'
            )
            ->getResult();
        return $data;
    }
}
