<?php

namespace JfxNinja\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DomainsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainsRepository extends EntityRepository
{

    public function findBySecurekey($securekey)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM JfxNinjaCMSBundle:Domain c WHERE c.securekey = :securekey'
            )->setParameter('securekey', $securekey)
            ->getSingleResult();
    }

    public function getDomain($host)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM JfxNinjaCMSBundle:Domain c WHERE c.domain LIKE :host'
            )->setParameter('host', "%".$host."%")
            ->getSingleResult();
    }


    public function getItemsForListTable()
    {
        $data['type'] = "Field Types";
        $data['columns'] = array(
            "Name"=>"name",
            "Domain"=>"domain",
            "Last Modified"=>"modifiedAt",
            "Last Modified By"=>"modifiedBy",
        );
        $data['items'] = $this->getEntityManager()
            ->createQuery(
                'SELECT
                c.name,
                c.domain,
                c.securekey,
                c.modifiedAt,
                c.modifiedBy
                FROM JfxNinjaCMSBundle:Domain c ORDER BY c.name ASC'
            )
            ->getResult();
        return $data;
    }

}
