<?php

namespace SSone\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FieldContentOptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldContentOptionsRepository extends EntityRepository
{


    public function findBySecurekey($securekey)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM SSoneCMSBundle:FieldContentOptions c WHERE c.securekey = :securekey'
            )->setParameter('securekey', $securekey)
            ->getSingleResult();
    }


    public function getItemsForListTable()
    {
        $data['type'] = "Field Setup Options";
        $data['columns'] = array(
            "Option Name"=>"name",
            "Variable Name"=>"variableName",
            "Label"=>"label",
            "Input Type"=>"inputType",
            "Associated Field Type"=>"fieldType",
            "Input Variable"=>"inputTypeVar",
            "ID"=>"id"
        );

        $data['items'] = $this->getEntityManager()
            ->createQuery(
                'SELECT fs.name, fs.id, fs.securekey, fs.label, fs.variableName, fs.inputType, fs.inputTypeVar, ft.name AS fieldType
                FROM SSoneCMSBundle:FieldContentOptions fs
                LEFT JOIN fs.fieldType ft
                ORDER BY ft.name ASC, fs.fieldVar ASC, fs.name ASC'
            )
            ->getResult();

        return $data;
    }

    public function getAllFieldContentOptions()
    {

        $data = $this->getEntityManager()
            ->createQuery(
                'SELECT fs.name, fs.id, fs.label, fs.variableName, fs.inputType, fs.inputTypeVar, ft.name AS fieldType, ft.id AS fieldTypeId
                FROM SSoneCMSBundle:FieldContentOptions fs
                LEFT JOIN fs.fieldType ft
                ORDER BY ft.name ASC, fs.fieldVar ASC, fs.name ASC'
            )
            ->getResult();

        $options = array();
        foreach($data as $option)
        {
            $options[$option['fieldTypeId']]['options'][$option['variableName']] = $option;
            $options[$option['fieldTypeId']]['name'] = $option['fieldType'];
        }
        return $options;
    }
}
