<?php

namespace SSone\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DomainsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository
{

    public function findBySecurekey($securekey)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM SSoneCMSBundle:Language c WHERE c.securekey = :securekey'
            )->setParameter('securekey', $securekey)
            ->getSingleResult();
    }


    public function getItemsForListTable()
    {
        $data['type'] = "Field Types";
        $data['columns'] = array(
            "Name"=>"name",
            "Language Code"=>"languageCode",
            "Last Modified"=>"modifiedAt",
            "Last Modified By"=>"modifiedBy",
        );
        $data['items'] = $this->getEntityManager()
            ->createQuery(
                'SELECT
                c.name,
                c.languageCode,
                c.securekey,
                c.modifiedAt,
                c.modifiedBy
                FROM SSoneCMSBundle:Language c ORDER BY c.name ASC'
            )
            ->getResult();
        return $data;
    }

}
