<?php

namespace SSone\CMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolesRepository extends EntityRepository
{

    public function getRole($roleName)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM SSoneCMSBundle:Role c WHERE c.role = :role'
            )->setParameter('role', $roleName)
            ->getSingleResult();
    }

}
